# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 276ac88f05134960466f75075b598cf019e3a36ded8790c66292beb9dded27eb220959dc8f0f8f43da957949482975049805b8a898858f1a9e864c70ca801b82

test:
  secret_key_base: 216842bdad96735fbd4d5196a8cc9f6317dd86f933804cd29d2ba4247e25b45b9e25ec7c16a2fbe1e3e4536ec5a639e58702e465278b06c5aa295b46edc891f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
